export const projects = [
  {
    slug: "wenqu",
    number: "01",
    eyebrow: "AI READING PRODUCT",
    title: "问渠 Wenqu",
    summary: "不是另一个 PDF 聊天框，而是一间强调原文证据的 AI 陪读阅读室。",
    copy: "材料地图、双轨跟读、主动回忆、错因诊断与阅读档案，组成完整学习闭环。",
    tags: ["React 19", "FastAPI", "DeepSeek", "Supabase"],
    category: "AI 产品",
    href: "https://github.com/lizhuofan-curry/wenqu",
    demo: "https://wenqu-reading-room.vercel.app/",
    accent: "lime",
    signal: "LIVE / v.4",
    question: "如何让 AI 阅读回到原文，并让学习过程留下可复盘的证据？",
    role: "产品构想 · 全栈实现 · 学习闭环设计",
    highlights: ["材料地图：先建立全局位置，再进入局部阅读。", "双轨跟读：原文与理解并行，不把回答变成黑箱。", "阅读档案：把过程、错因与下一步学习建议留存下来。"],
  },
  {
    slug: "shop-vision",
    number: "02",
    eyebrow: "COMPUTER VISION SYSTEM",
    title: "智图寻宝 · Shop Vision",
    summary: "一次上传串起商品分类、图像去噪、同类检索与 AI 文案。",
    copy: "它不止训练模型，也把数据、权重、特征库、Web 推理和结果解释接成闭环。",
    tags: ["PyTorch", "Flask", "U-Net", "KNN"],
    category: "计算机视觉",
    href: "https://github.com/lizhuofan-curry/smart-image-treasure-hunt",
    accent: "orange",
    signal: "VAL ACC / 99.32%",
    question: "怎样把多个视觉能力组织成一个可理解、可实际操作的商品探索流程？",
    role: "视觉模型实验 · 推理服务 · 产品流程串联",
    highlights: ["上传后依次完成分类、去噪、相似商品检索与文案生成。", "模型权重与特征库进入同一条可运行的 Web 推理路径。", "99.32% 标注为验证集准确率，不将其表述为独立测试集结果。"],
  },
  {
    slug: "cnn-architectures",
    number: "03",
    eyebrow: "MODEL STUDY",
    title: "CNN × Inception × ResNet",
    summary: "在 CIFAR-10 上，用同一训练流程观察三种经典视觉网络。",
    copy: "分支通过 torch.cat 汇合，残差通过 F(x)+x 保留信息；代码、曲线与结论各自保留清晰证据边界。",
    tags: ["CIFAR-10", "torch.cat", "Residual", "20 epochs"],
    category: "深度学习",
    href: "https://github.com/lizhuofan-curry/LiuErDaRenPyTorch/tree/main/Chapter11_AdvancedCNN/CIFAR10_Three_CNN_Architectures",
    accent: "blue",
    signal: "3 ARCHITECTURES",
    question: "当训练条件一致时，网络的连接方式究竟改变了什么？",
    role: "实验复现 · 结构阅读 · 结果证据整理",
    highlights: ["同一 CIFAR-10 训练流程下对照 CNN、Inception 与 ResNet。", "Inception 用 torch.cat(..., dim=1) 合并多尺度分支。", "ResNet 用 out += identity 建立残差路径；验证曲线不替代测试结论。"],
  },
  {
    slug: "llm-fullstack",
    number: "04",
    eyebrow: "LLM ENGINEERING LOG",
    title: "LLM FullStack Journey",
    summary: "从可运行的 AI Study Coach 出发，记录 LLM 工程的迭代过程。",
    copy: "持续扩展 Provider、测试、CI、RAG 与 Agent 工作流，把想法变成可靠软件。",
    tags: ["Python", "FastAPI", "LLM", "LangGraph"],
    category: "LLM 工程",
    href: "https://github.com/lizhuofan-curry/LLM-FullStack-Journey",
    accent: "violet",
    signal: "BUILD → TEST → LEARN",
    question: "一个 LLM 想法如何从能对话，走向能验证、能维护的系统？",
    role: "后端工程 · Provider 探索 · 测试与工作流设计",
    highlights: ["从 AI Study Coach 的可运行原型开始。", "继续补齐 Provider、测试、CI、RAG 与 Agent 工作流。", "用工程记录保存每次构建、检查与学习的上下文。"],
  },
];

export const notes = [
  { number: "01", title: "把 Traceback 变成下一步", tag: "DEBUGGING", lead: "报错信息不是噪音。先定位真正失败的一行，再检查环境、输入形状与调用链。", points: ["先读最后一个异常，再向上回溯。", "用最小前向传播复现，而不是一上来改整段训练。"] },
  { number: "02", title: "Inception：分支如何汇合", tag: "ARCHITECTURE", lead: "不同感受野同时观察同一输入，最后沿通道维度拼接：torch.cat(branches, dim=1)。", points: ["每条分支的空间尺寸必须对齐。", "拼接后通道数是各分支通道数之和。"] },
  { number: "03", title: "ResNet：为什么要保留 identity", tag: "ARCHITECTURE", lead: "残差块让网络学习 F(x)，同时保留 x：out += identity。", points: ["当尺寸或通道不匹配时，需要投影分支。", "残差连接是信息路径，不是性能承诺。"] },
  { number: "04", title: "验证集不是测试集", tag: "EVIDENCE", lead: "验证集用于模型选择与调参；没有独立测试过程，就不把验证指标称为最终泛化结果。", points: ["记录数据划分、随机种子和训练设置。", "让图表、脚本和文字结论彼此可追溯。"] },
];

export function getProject(slug) {
  return projects.find((project) => project.slug === slug);
}
