import { SiteFooter, SiteHeader } from "../_components/SiteHeader";

const cases = [
  { id: "01", tag: "ENVIRONMENT", code: "WinError 4551", title: "导入失败，未必是模型的错。", symptom: "PyTorch 在导入阶段加载 DLL 失败，训练代码甚至还没有开始运行。", trace: "先确认 Python 解释器与报错路径，再检查 Windows 的应用控制或代码完整性策略。", lesson: "在改模型之前，先区分环境阻塞和代码错误。", evidence: "排查重点：Code Integrity / App Control 事件与 DLL 签名状态。" },
  { id: "02", tag: "KERNEL", code: "wrong interpreter", title: "切了环境，不代表内核已经切过去。", symptom: "Notebook 元数据指向 pytorch_learn，但 Traceback 却来自另一个 Python 路径。", trace: "比对正在运行的解释器、Notebook 内核与 Traceback 文件路径；环境调整后执行 Restart Kernel + Run All。", lesson: "先确认“谁在运行代码”，再判断依赖与版本。", evidence: "同一安全策略阻止多个解释器时，单纯切换环境并不能绕过问题。" },
  { id: "03", tag: "SPATIAL SIZE", code: "missing padding=1", title: "尺寸悄悄缩小，后面才会爆炸。", symptom: "连续 3×3 卷积没有 padding，特征图不断缩小，后续层的空间尺寸和预期不一致。", trace: "从输入开始写下每层的 H×W；对于需要保持尺寸的 3×3 卷积，检查是否显式设置 padding=1。", lesson: "先用纸面形状推导，再相信运行结果。", evidence: "结构阅读的第一步不是参数量，而是通道和空间尺寸。" },
  { id: "04", tag: "SHAPE", code: "Conv2d channel mismatch", title: "通道对不上，网络就不会说话。", symptom: "卷积层期待的输入通道数，与前一层真正输出的通道数不一致。", trace: "沿着前向传播逐层标注形状，检查每个 Conv2d 的 in_channels 是否接住上一层。", lesson: "Shape aware：每一层的通道与空间尺寸都要有据可查。", evidence: "用干净进程做一次最小前向传播，比在整段训练里猜更可靠。" },
  { id: "05", tag: "TRAINING LOOP", code: "model(images)", title: "不报错的训练，也可能在训练错对象。", symptom: "验证阶段仍调用固定模型变量，或训练循环提前 return，导致函数表面完成、实际没有完整跑完。", trace: "检查 return 的缩进位置；训练和验证都通过传入的 model 执行前向传播。", lesson: "能跑不等于逻辑正确；要看完整控制流。", evidence: "同时核对 loss 累积时是否乘以真实 batch size，避免平均损失失真。" },
  { id: "06", tag: "EVIDENCE", code: "validation ≠ test", title: "曲线漂亮，不等于结论成立。", symptom: "把验证集指标写成测试结果，或者忽略数据划分、随机种子与训练设置。", trace: "回到数据划分、训练设置和原始输出，明确结果到底来自哪一步。", lesson: "Evidence > claims：结论的强度不能超过证据。", evidence: "CIFAR-10 实验使用 45,000 训练 / 5,000 验证 / 10,000 测试；若未输出测试准确率，就不把验证曲线包装成测试结论。" },
];

export const metadata = { title: "报错博物馆 — Zhuofan Li" };

export default function MuseumPage() { return <main className="knowledge-page"><SiteHeader /><section className="page-hero museum-hero"><p className="label">05 / TRACEBACK MUSEUM</p><h1>每一个报错，<br /><em>都是一件展品。</em></h1><p>不把失败藏起来：保存症状、排查路径与留下来的判断规则。</p></section><section className="museum-intro"><p>点击一张卡片，展开这次调试从「现象」到「线索」再到「规则」的过程。</p><span>06 EXHIBITS · REAL OUTPUTS</span></section><section className="museum-grid">{cases.map((item) => <details className="museum-card" key={item.id}><summary><div><span>{item.id}</span><span>{item.tag}</span></div><code>{item.code}</code><h2>{item.title}</h2><span className="museum-open">打开展签 ↓</span></summary><div className="museum-detail"><div><span>SYMPTOM</span><p>{item.symptom}</p></div><div><span>TRACE</span><p>{item.trace}</p></div><div><span>TAKEAWAY</span><p>{item.lesson}</p></div><div><span>EVIDENCE</span><p>{item.evidence}</p></div></div></details>)}</section><SiteFooter /></main>; }
